spring:
  redis:
    host: 172.0.0.1
    #assword: 123456
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/usersinfo
      username: root
      password: root
  application:
    name: springcloud-provider-config
  profiles:
    active: production
logging:
  level:
    root: info
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.yasaka.stock : debug
server:
  port: 8763
